/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSourcesRouteImport } from './routes/app/sources'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthCheckEmailRouteImport } from './routes/_auth/check-email'
import { Route as legalLayoutRouteImport } from './routes/(legal)/_layout'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as ApiImgStorageIdRouteImport } from './routes/api/img.$storageId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as legalLayoutTermsRouteImport } from './routes/(legal)/_layout/terms'
import { Route as legalLayoutPrivacyRouteImport } from './routes/(legal)/_layout/privacy'
import { Route as legalLayoutCookiesRouteImport } from './routes/(legal)/_layout/cookies'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const legalLayoutRoute = legalLayoutRouteImport.update({
  id: '/(legal)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiImgStorageIdRoute = ApiImgStorageIdRouteImport.update({
  id: '/api/img/$storageId',
  path: '/api/img/$storageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const legalLayoutTermsRoute = legalLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => legalLayoutRoute,
} as any)
const legalLayoutPrivacyRoute = legalLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => legalLayoutRoute,
} as any)
const legalLayoutCookiesRoute = legalLayoutCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => legalLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/app/admin': typeof AppAdminRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/sources': typeof AppSourcesRoute
  '/app/': typeof AppIndexRoute
  '/cookies': typeof legalLayoutCookiesRoute
  '/privacy': typeof legalLayoutPrivacyRoute
  '/terms': typeof legalLayoutTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/img/$storageId': typeof ApiImgStorageIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/app/admin': typeof AppAdminRoute
  '/app/library': typeof AppLibraryRoute
  '/app/sources': typeof AppSourcesRoute
  '/app': typeof AppIndexRoute
  '/cookies': typeof legalLayoutCookiesRoute
  '/privacy': typeof legalLayoutPrivacyRoute
  '/terms': typeof legalLayoutTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/img/$storageId': typeof ApiImgStorageIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/(legal)/_layout': typeof legalLayoutRouteWithChildren
  '/_auth/check-email': typeof AuthCheckEmailRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/admin': typeof AppAdminRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/sources': typeof AppSourcesRoute
  '/app/': typeof AppIndexRoute
  '/(legal)/_layout/cookies': typeof legalLayoutCookiesRoute
  '/(legal)/_layout/privacy': typeof legalLayoutPrivacyRoute
  '/(legal)/_layout/terms': typeof legalLayoutTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/img/$storageId': typeof ApiImgStorageIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/pricing'
    | '/check-email'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/app/admin'
    | '/app/library'
    | '/app/settings'
    | '/app/sources'
    | '/app/'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/api/img/$storageId'
    | '/app/settings/billing'
    | '/app/settings/profile'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/check-email'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/app/admin'
    | '/app/library'
    | '/app/sources'
    | '/app'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/api/img/$storageId'
    | '/app/settings/billing'
    | '/app/settings/profile'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/pricing'
    | '/(legal)/_layout'
    | '/_auth/check-email'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/app/admin'
    | '/app/library'
    | '/app/settings'
    | '/app/sources'
    | '/app/'
    | '/(legal)/_layout/cookies'
    | '/(legal)/_layout/privacy'
    | '/(legal)/_layout/terms'
    | '/api/auth/$'
    | '/api/img/$storageId'
    | '/app/settings/billing'
    | '/app/settings/profile'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
  legalLayoutRoute: typeof legalLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImgStorageIdRoute: typeof ApiImgStorageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sources': {
      id: '/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/check-email': {
      id: '/_auth/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(legal)/_layout': {
      id: '/(legal)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legalLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/img/$storageId': {
      id: '/api/img/$storageId'
      path: '/api/img/$storageId'
      fullPath: '/api/img/$storageId'
      preLoaderRoute: typeof ApiImgStorageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/_layout/terms': {
      id: '/(legal)/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalLayoutTermsRouteImport
      parentRoute: typeof legalLayoutRoute
    }
    '/(legal)/_layout/privacy': {
      id: '/(legal)/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalLayoutPrivacyRouteImport
      parentRoute: typeof legalLayoutRoute
    }
    '/(legal)/_layout/cookies': {
      id: '/(legal)/_layout/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof legalLayoutCookiesRouteImport
      parentRoute: typeof legalLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSourcesRoute: typeof AppSourcesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSourcesRoute: AppSourcesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface legalLayoutRouteChildren {
  legalLayoutCookiesRoute: typeof legalLayoutCookiesRoute
  legalLayoutPrivacyRoute: typeof legalLayoutPrivacyRoute
  legalLayoutTermsRoute: typeof legalLayoutTermsRoute
}

const legalLayoutRouteChildren: legalLayoutRouteChildren = {
  legalLayoutCookiesRoute: legalLayoutCookiesRoute,
  legalLayoutPrivacyRoute: legalLayoutPrivacyRoute,
  legalLayoutTermsRoute: legalLayoutTermsRoute,
}

const legalLayoutRouteWithChildren = legalLayoutRoute._addFileChildren(
  legalLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
  legalLayoutRoute: legalLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImgStorageIdRoute: ApiImgStorageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
